-- schema.sql
DROP TABLE IF EXISTS ENTITY;

CREATE TABLE ENTITY(
   ID BIGINT AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR (250) NOT NULL,
   DESCRIPTION VARCHAR (250) NOT NULL
);

DROP TABLE IF EXISTS FILE;

CREATE TABLE FILE(
   ID BIGINT AUTO_INCREMENT PRIMARY KEY,
   FILENAME VARCHAR (250) NOT NULL,
   FILEURI VARCHAR (250) NOT NULL,
   ID_ENTITY BIGINT,
   FILE BINARY (1000) NOT NULL,
   FOREIGN KEY (ID_ENTITY) REFERENCES ENTITY(ID)
);